### PR TITLE
Minor fixes

### LINKED ISSUE #195: Swamps seems half a tile off
Reported by Robalian on slack 
image

### PR DESCRIPTION
**Pull request by Gadjung**
Fixes #195

### CODE REVIEW

File: Assets/Scripts/Screeps3D/Effects/AttackEffect.cs [hunk 1]
```diff
@@ -13,10 +13,14 @@ public class AttackEffect : MonoBehaviour
...
         private Vector3 _target;
         
-        public void Load(Vector3 target)
+        public void Load(Vector3 target, Color? color)
         {
             _target = target;
             _time = 0f;
+            if(color != null) {
+                ParticleSystem.MainModule settings = _attackParticles.main;
+                settings.startColor = Color.blue;
```
Comment (thmsndk) [inline Assets/Scripts/Screeps3D/Effects/AttackEffect.cs]: Should this not be the color variable instead of blue? does not seem like the color argument is used?

File: Assets/Scripts/Screeps3D/RoomObjects/UnpackUtility.cs [hunk 2]
```diff
@@ -291,13 +291,20 @@ internal static void Store(IStoreObject obj, JSONObject data)
         internal static void ActionLog(IActionObject actionObject, JSONObject data)
         {
             var actionLog = data["actionLog"];
+            var creep = actionObject as Creep;
```
Comment (thmsndk) [inline Assets/Scripts/Screeps3D/RoomObjects/UnpackUtility.cs]: no reason for this, was part of debug :)

File: Assets/Scripts/Screeps3D/RoomObjects/Views/CreepActionView.cs [hunk 3]
```diff
@@ -156,9 +155,12 @@ public void Unload(RoomObject roomObject)
         private void doAura(string auraType, Color32 auraColor) {
             var target = _creep.Actions[auraType];
             switch(auraType) {
+                case "rangedAttack":
```
Comment (thmsndk) [inline Assets/Scripts/Screeps3D/RoomObjects/Views/CreepActionView.cs:158]: A little confused, is rangedAttack an aura?

**Review by thmsndk — CHANGES_REQUESTED** [review]

File: Assets/Scripts/Screeps3D/Effects/AttackEffect.cs (hunk 1 above)
Comment (Gadjung) [reply Assets/Scripts/Screeps3D/Effects/AttackEffect.cs]: for now it's hardcoded to see if it works (it does not - i need to change trail color)

File: Assets/Scripts/Screeps3D/RoomObjects/UnpackUtility.cs (hunk 2 above)
Comment (Gadjung) [reply Assets/Scripts/Screeps3D/RoomObjects/UnpackUtility.cs]: will remove

File: Assets/Scripts/Screeps3D/RoomObjects/Views/CreepActionView.cs (hunk 3 above)
Comment (Gadjung) [reply Assets/Scripts/Screeps3D/RoomObjects/Views/CreepActionView.cs:158]: it's more like it triggers an aura-like effect

Comment (Gadjung) [reply Assets/Scripts/Screeps3D/RoomObjects/Views/CreepActionView.cs:158]: it still triggers beam effect

**Comment by thmsndk** [comment]
Should fix #195

**Review by thmsndk — APPROVED** [review]
